### ISSUE TITLE
I NewPlace görs kontrollen om platsen redan finns också med positionMap.values() 

### ISSUE THREAD

**Issue by OliviaImner** [OliviaImner/AssignmentMap#9]
Fast du har en hashmap med position som nyckel... även senare i samma metod går du igenom alla platser och gör setLocked(). Verkar kanske onödigt.

**Comment by jasonserviss** [comment]
If there is duplicate functionality here then, if possible, one should be removed. If the hash map with position as the key is ONLY used for checking if a place exists, then it can be removed. Instead of removing things directly, comment them out and check CAREFULLY that the program still works. I don't think this comment is high priority either....

**Comment by OliviaImner** [comment]
ea199cbc74a2ee82de6fd46b606b1c2de434c7fb
